name: Shlink Web Client
version: "0.1.0"
slug: shlink-web-client
description: >
  A Home Assistant Addon to run the Shlink Web Client (UI) via Docker.
    
startup: services
boot: auto
options: {}
schema: {}
