
name: "Shlink Web Client"
slug: "shlink-web-client"
description: "Offizieller Shlink Web Client (Ingress in Home Assistant)"
version: "latest"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: application
stage: stable
url: "https://shlink.io/documentation/shlink-web-client/"

# Offizielles Docker-Image nutzen
image: "shlinkio/shlink-web-client:latest"
legacy: true

# Ingress-Panel
ingress: true
ingress_port: 8080
panel_icon: "mdi:link-variant"
panel_title: "Shlink"

# Keine externe Portfreigabe
portsports:

