
name: "Shlink Web Client"
slug: "shlink_web_client"
description: "Offizieller Shlink Web Client (Ingress in Home Assistant)"
version: "1.0.0"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: application
stage: stable
url: "https://shlink.io/documentation/shlink-web-client/"

# Ingress-Panel (Shlink Web Client bedient Port 8080)
ingress: true
ingress_port: 8080
panel_icon: "mdi:link-variant"
panel_title: "Shlink"

## Keine externe Portfreigabe (Ingress reicht)
ports:

