name: "Shlink Web Client"
version: "1.0.0"
slug: "shlink_web_client"
description: "Grafisches Frontend zur Verwaltung des Shlink URL Shorteners."
url: "https://shlink.io/web-client"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
host_network: true
# Port 8081 f√ºr den Web Client
ports:
  8081/tcp: 8081 
# Wir brauchen hier keine /data, da es ein statisches Frontend ist
map:
  - config:rw 

options:
  shlink_api_url: "http://localhost:8080"
schema:
  shlink_api_url: str # Die Adresse des ersten Shlink Add-ons
